FROM python:3.12-slim

RUN apt update && apt install -y git && apt clean

# Creates application directory
WORKDIR /app

# Creates an appuser and change the ownership of the application's folder
RUN useradd appuser && \
    chown appuser ./ && \
    pip install --only-binary=:all: --upgrade "pip==26.1.2" && \
    pip install --only-binary=:all: "poetry==2.4.1" && \
    poetry config virtualenvs.create false --local

# Copy dependency definition to cache
COPY --chown=appuser poetry.lock pyproject.toml ./

# Installs projects dependencies as a separate layer
RUN poetry install --no-root

# Copies and chowns for the userapp on a single layer
COPY --chown=appuser . ./
